
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 21 12:02:08 CST 2011
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 8;
  public static final int ASSIGNMENT = 45;
  public static final int ASTERISK = 34;
  public static final int SLASH = 35;
  public static final int RIGHT_SQUARE_BRACKET = 28;
  public static final int VERTICAL_BAR = 44;
  public static final int ARRAY = 2;
  public static final int FOR = 7;
  public static final int MINUS = 33;
  public static final int SEMICOLON = 24;
  public static final int LT = 39;
  public static final int TYPE = 16;
  public static final int NIL = 12;
  public static final int NEGATIVE = 36;
  public static final int IN = 10;
  public static final int COMMA = 22;
  public static final int GEQ = 42;
  public static final int RIGHT_PARENTHESIS = 26;
  public static final int PLUS = 32;
  public static final int LEFT_CURLY_BRACKET = 29;
  public static final int IF = 9;
  public static final int AMPERSAND = 43;
  public static final int DOT = 31;
  public static final int OF = 13;
  public static final int EOF = 0;
  public static final int LEFT_SQUARE_BRACKET = 27;
  public static final int error = 1;
  public static final int NEQ = 38;
  public static final int BREAK = 3;
  public static final int EQ = 37;
  public static final int COLON = 23;
  public static final int ELSE = 5;
  public static final int STRING_CONSTANT = 20;
  public static final int TO = 15;
  public static final int WHILE = 18;
  public static final int LET = 11;
  public static final int THEN = 14;
  public static final int LEQ = 40;
  public static final int END = 6;
  public static final int GT = 41;
  public static final int RIGHT_CURLY_BRACKET = 30;
  public static final int VAR = 17;
  public static final int LEFT_PARENTHESIS = 25;
  public static final int DO = 4;
  public static final int INTEGER_CONSTANT = 21;
  public static final int IDENTIFIER = 19;
}

